name: Manual Trigger Windows

on: 
  workflow_dispatch:

jobs:
  release-version:
    runs-on: windows-latest
    environment: production
    steps:
      - name: Relase
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: go version  
